workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1

    environment:
      node: 22

    scripts:
  - name: Build iOS Simulator
    script: |
      xcodebuild \
        -project Sihhatk.xcodeproj \
        -scheme Sihhatk \
        -sdk iphonesimulator \
        -configuration Debug \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGNING_REQUIRED=NO
    artifacts:
      - ios/**/*.app
      - ios/**/*.ipa
