workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1

    environment:
      node: 22

    scripts:
      - xcodebuild
      - npx cap sync ios
      - xcodebuild -workspace ios/App/App.xcodeproj/project.xcworkspace -scheme App -configuration Release -sdk iphonesimulator build

    artifacts:
      - ios/**/*.app
      - ios/**/*.ipa
